# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: options.proto

import sys
_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='options.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\roptions.proto\"\xb4\x03\n\x18SkeletonsDetectorOptions\x12\x12\n\nbroker_uri\x18\x01 \x01(\t\x12\x13\n\x0bzipkin_host\x18\x02 \x01(\t\x12\x13\n\x0bzipkin_port\x18\x03 \x01(\r\x12\x19\n\x11zipkin_batch_size\x18\x04 \x01(\r\x12=\n\tmediapipe\x18\x05 \x01(\x0b\x32*.SkeletonsDetectorOptions.MediapipeOptions\x12\x30\n\x06resize\x18\x06 \x01(\x0b\x32 .SkeletonsDetectorOptions.Resize\x1a\'\n\x06Resize\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x1a\xa4\x01\n\x10MediapipeOptions\x12\x19\n\x11static_image_mode\x18\x01 \x01(\x08\x12\x18\n\x10model_complexity\x18\x02 \x01(\x05\x12\x18\n\x10smooth_landmarks\x18\x03 \x01(\x08\x12 \n\x18min_detection_confidence\x18\x04 \x01(\x02\x12\x1f\n\x17min_tracking_confidence\x18\x05 \x01(\x02\x62\x06proto3')
)


_SKELETONSDETECTOROPTIONS_RESIZE = _descriptor.Descriptor(
  name='Resize',
  full_name='SkeletonsDetectorOptions.Resize',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='SkeletonsDetectorOptions.Resize.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='SkeletonsDetectorOptions.Resize.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[],
  nested_types=[],
  enum_types=[],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[],
  serialized_start=248,
  serialized_end=287,
)


_SKELETONSDETECTOROPTIONS_MEDIAPIPEOPTIONS = _descriptor.Descriptor(
  name='MediapipeOptions',
  full_name='SkeletonsDetectorOptions.MediapipeOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='static_image_mode', full_name='SkeletonsDetectorOptions.MediapipeOptions.static_image_mode', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_complexity', full_name='SkeletonsDetectorOptions.MediapipeOptions.model_complexity', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='smooth_landmarks', full_name='SkeletonsDetectorOptions.MediapipeOptions.smooth_landmarks', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_detection_confidence', full_name='SkeletonsDetectorOptions.MediapipeOptions.min_detection_confidence', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_tracking_confidence', full_name='SkeletonsDetectorOptions.MediapipeOptions.min_tracking_confidence', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[],
  nested_types=[],
  enum_types=[],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[],
  serialized_start=290,
  serialized_end=454,
)


_SKELETONSDETECTOROPTIONS = _descriptor.Descriptor(
  name='SkeletonsDetectorOptions',
  full_name='SkeletonsDetectorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='broker_uri', full_name='SkeletonsDetectorOptions.broker_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zipkin_host', full_name='SkeletonsDetectorOptions.zipkin_host', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zipkin_port', full_name='SkeletonsDetectorOptions.zipkin_port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zipkin_batch_size', full_name='SkeletonsDetectorOptions.zipkin_batch_size', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mediapipe', full_name='SkeletonsDetectorOptions.mediapipe', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resize', full_name='SkeletonsDetectorOptions.resize', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[],
  nested_types=[_SKELETONSDETECTOROPTIONS_RESIZE, _SKELETONSDETECTOROPTIONS_MEDIAPIPEOPTIONS],
  enum_types=[],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[],
  serialized_start=18,
  serialized_end=454,
)

_SKELETONSDETECTOROPTIONS_RESIZE.containing_type = _SKELETONSDETECTOROPTIONS
_SKELETONSDETECTOROPTIONS_MEDIAPIPEOPTIONS.containing_type = _SKELETONSDETECTOROPTIONS
_SKELETONSDETECTOROPTIONS.fields_by_name['mediapipe'].message_type = _SKELETONSDETECTOROPTIONS_MEDIAPIPEOPTIONS
_SKELETONSDETECTOROPTIONS.fields_by_name['resize'].message_type = _SKELETONSDETECTOROPTIONS_RESIZE
DESCRIPTOR.message_types_by_name['SkeletonsDetectorOptions'] = _SKELETONSDETECTOROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SkeletonsDetectorOptions = _reflection.GeneratedProtocolMessageType('SkeletonsDetectorOptions', (_message.Message,), dict(

  Resize = _reflection.GeneratedProtocolMessageType('Resize', (_message.Message,), dict(
    DESCRIPTOR = _SKELETONSDETECTOROPTIONS_RESIZE,
    __module__ = 'options_pb2'
    # @@protoc_insertion_point(class_scope:SkeletonsDetectorOptions.Resize)
    )),

  MediapipeOptions = _reflection.GeneratedProtocolMessageType('MediapipeOptions', (_message.Message,), dict(
    DESCRIPTOR = _SKELETONSDETECTOROPTIONS_MEDIAPIPEOPTIONS,
    __module__ = 'options_pb2'
    # @@protoc_insertion_point(class_scope:SkeletonsDetectorOptions.MediapipeOptions)
    )),

  DESCRIPTOR = _SKELETONSDETECTOROPTIONS,
  __module__ = 'options_pb2'
  # @@protoc_insertion_point(class_scope:SkeletonsDetectorOptions)
  ))
_sym_db.RegisterMessage(SkeletonsDetectorOptions)
_sym_db.RegisterMessage(SkeletonsDetectorOptions.Resize)
_sym_db.RegisterMessage(SkeletonsDetectorOptions.MediapipeOptions)


# @@protoc_insertion_point(module_scope)
