# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\roptions.proto\"\xb4\x03\n\x18SkeletonsDetectorOptions\x12\x12\n\nbroker_uri\x18\x01 \x01(\t\x12\x13\n\x0bzipkin_host\x18\x02 \x01(\t\x12\x13\n\x0bzipkin_port\x18\x03 \x01(\r\x12\x19\n\x11zipkin_batch_size\x18\x04 \x01(\r\x12=\n\tmediapipe\x18\x05 \x01(\x0b\x32*.SkeletonsDetectorOptions.MediapipeOptions\x12\x30\n\x06resize\x18\x06 \x01(\x0b\x32 .SkeletonsDetectorOptions.Resize\x1a\'\n\x06Resize\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x1a\xa4\x01\n\x10MediapipeOptions\x12\x19\n\x11static_image_mode\x18\x01 \x01(\x08\x12\x18\n\x10model_complexity\x18\x02 \x01(\x05\x12\x18\n\x10smooth_landmarks\x18\x03 \x01(\x08\x12 \n\x18min_detection_confidence\x18\x04 \x01(\x02\x12\x1f\n\x17min_tracking_confidence\x18\x05 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SKELETONSDETECTOROPTIONS']._serialized_start=18
  _globals['_SKELETONSDETECTOROPTIONS']._serialized_end=454
  _globals['_SKELETONSDETECTOROPTIONS_RESIZE']._serialized_start=248
  _globals['_SKELETONSDETECTOROPTIONS_RESIZE']._serialized_end=287
  _globals['_SKELETONSDETECTOROPTIONS_MEDIAPIPEOPTIONS']._serialized_start=290
  _globals['_SKELETONSDETECTOROPTIONS_MEDIAPIPEOPTIONS']._serialized_end=454
# @@protoc_insertion_point(module_scope)
