FROM tensorflow/tensorflow:2.13.0-gpu

RUN pip uninstall -y jupyter ipykernel                               \
 && rm -rf /notebooks                                                \ 
 && rm -f /run_jupyter.sh                                            \
 && rm -f /root/.jupyter/jupyter_notebook_config.py                  \
 && rm -f /tensorflow_gpu-2.13.0-cp38-cp38-manylinux2010_x86_64.whl

RUN apt-get update && apt-get install -y --no-install-recommends \
    git wget libsm6 libxext6 libxrender-dev 

RUN cd /tmp                                                  \
 && git clone https://github.com/jiajunhua/ildoonet-tf-pose-estimation \
 && cd ildoonet-tf-pose-estimation                                   \
 && cd models/graph/cmu/ && bash download.sh && cd ../../../ \
 && pip install --user .

RUN rm -rf /tmp/*